services:
  traefik:
    image: traefik:v3.0.0-rc1
    command: --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: traefik/whoami:latest
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)"
      - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"

  traefik-forward-auth:
    image: ghcr.io/dsbferris/traefik-forward-auth:latest
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=<YOUR-CLIENT-ID>
      - PROVIDERS_GOOGLE_CLIENT_SECRET=<YOUR-CLIENT-SECRET>
      - SECRET=<SOME-SECRET>
      - INSECURE_COOKIE=true # required, even if using websecure
      - COOKIE_DOMAIN=example.com
      - AUTH_HOST=auth.example.com
      # - LOG_LEVEL=debug
    labels:
      traefik.http.services.traefik-forward-auth.loadbalancer.server.port: 4181
      traefik.http.routers.traefik-forward-auth.rule: Host(`auth.example.com`)
      # using websecure to be more clear about INSECURE_COOKIE
      traefik.http.routers.traefik-forward-auth.entrypoints: websecure 
      
      # keep address like that. dont think about changing it to "https://auth.example.com"
      # I spend a whole evening trying out many ways to get rid of INSECURE_COOKIE
      # haven't found one...
      traefik.http.middlewares.traefik-forward-auth.forwardauth.address: http://traefik-forward-auth:4181
      traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders: X-Forwarded-User
