version: '3'

services:
  traefik:
    image: traefik:1.7
    command: -c /traefik.toml
    ports:
      - "8085:80"
      - "8086:8080"
    networks:
      - traefik
    volumes:
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    image: containous/whoami
    networks:
      - traefik
    labels:
      - "traefik.backend=whoami"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:whoami.localhost.com"

  traefik-forward-auth:
    build: thomseddon/traefik-forward-auth:2
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=https://login.microsoftonline.com/{tenant}
      - PROVIDERS_OIDC_CLIENT_ID=your-client-id
      - PROVIDERS_OIDC_CLIENT_SECRET=your-client-secret
      - SECRET=something-random
      - INSECURE_COOKIE=true
      - DOMAIN=yourcompany.com
      - LOG_LEVEL=debug
    networks:
      - traefik

networks:
  traefik:
